# Generated by Django 5.2 on 2025-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maain_app', '0002_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
