# Generated by Django 5.2 on 2025-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maain_app', '0003_customer_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
